platform :ios, '9.0'

source 'https://mirrors.bfsu.edu.cn/git/CocoaPods/Specs.git'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
end

target 'testSh' do

pod 'QY_iOS_SDK', '~> 5.11.0'

end


